#!/bin/sh

exec /usr/bin/spectrwm & wmpid=$!
setxkbmap gb -option 'caps:swapescape,ctrl:menu_rctrl,lv3:ralt_alt,terminate:ctrl_alt_bksp'

if [ $(hostname) = "paddy" ]; then
        xmodmap ~/.Xmodmap
        xinput set-prop 13 'Device Accel Profile' 6
        xinput set-prop 13 'Evdev Wheel Emulation' 1
        xinput set-prop 13 'Evdev Wheel emulation Button' 2
        xset s 80 dpms 85 90 95
        #synclient TouchpadOff=1
elif [ $(hostname) = "archy" ]; then
       xset s 120 dpms 125 130 135 
fi

xset r rate 345 53 +fp '/usr/share/fonts/local' fp rehash
xrdb ~/.Xresources
urxvt -e tmux attach &

#feh --bg-fill /home/toby/img/wallpapers/galaxy.jpg
#eval "$(gpg-agent --daemon)"

sleep 20; parcellite -d -n & 
sleep 40; dropbox start &
sleep 60; /home/toby/Dropbox/bin/zzzsysd &

wait $wmpid
